version: '3'

services:
  wings:
    image: "dockerpedia/wings-base"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      WINGS_MODE: dind
    volumes:
      - wings_data:/opt/wings
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080

volumes:
  wings_data:
